### ISSUE TITLE
Can't Add Card

### ISSUE THREAD

**Issue by Damiexxi** [zsarnett/Custom-Grid-View#2]
Hey,

I did everything in the tutorial but I can't add a card...nothing happens when I click the +

**Comment by zsarnett** [comment]
You may need to update to 2020.12

**Comment by Damiexxi** [comment]
> You may need to update to 2020.12

Thanks bro...did that and it's working 👍

**Comment by msauto** [comment]
Make sure that you make copies like he said. Any time that i add a card and sometimes when i edit a card  my entire view goes black and is not recoverable without copy and past raw config files back into that tabs view(which is very hard because it seems that  when grid-dnd is added  the information is moved around.) Best to get all cards added and edited then add custom: grid-dnd entry to move them around and resize. MAKE SURE YOU BACK UP AND OR COPY. Still cool as heck though.

**Comment by zsarnett** [comment]
Fixed in 0.0.3
